# Generated by Django 5.2.7 on 2025-10-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title1',
        ),
    ]
