# Generated by Django 5.2.7 on 2025-10-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_title_article_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title1',
            new_name='title',
        ),
    ]
