# Generated by Django 5.2.7 on 2025-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_title1_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('delete', 'Удаленная')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
