# Generated by Django 5.2.7 on 2025-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags_old',
            field=models.ManyToManyField(blank=True, related_name='articles_old', through='webapp.ArticleTag', through_fields=('article', 'tag'), to='webapp.tag', verbose_name='Теги'),
        ),
    ]
