# Generated by Django 5.2.7 on 2025-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_article_tags_article_tags_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.tag', verbose_name='Теги'),
        ),
    ]
