# Generated by Django 5.2.7 on 2025-11-12 13:33

from django.db import migrations

def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    Tag.objects.create(name='JS')
    Tag.objects.create(name='PHP')
    Tag.objects.create(name='Java')

def rollback(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    for tag in Tag.objects.filter(name__in=['JS', 'PHP', 'Java']):
        tag.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.RunPython(create_default_tags, rollback),
    ]
