# Generated by Django 5.2.7 on 2025-11-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_create_default_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
