# Generated by Django 5.2.7 on 2025-11-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('сan_have_piece_of_pizza', 'Может съесть кусочек пиццы')]},
        ),
    ]
